name: CI Pipeline

# Definindo quando o pipeline será acionado
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'  # Pode ser 'adoptopenjdk', 'zulu', 'amazon', 'openjdk', etc.

      # Instalar o Docker e Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker --version
          docker-compose --version

      # Instalar dependências e rodar testes
      - name: Run tests
        run: mvn clean install -DskipTests

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Rodar o docker-compose (opcional, conforme necessário)
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d