name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      # Instalar Docker e Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          sudo mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc

          # Corrigido aqui: vamos criar o arquivo docker.list corretamente
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          # Instalar Docker Compose (versão 1.x ou 2.x)
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Iniciar o serviço Docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Verificar as versões
          docker --version
          docker-compose --version

      # Instalar dependências e rodar testes
      - name: Run tests
        run: mvn clean install -DskipTests

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Rodar o docker-compose
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
